import Head from 'next/head';
import { Banner, NavBar } from '@/components';

import styles from '../styles/Home.module.scss';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Nextflix</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<NavBar username="albina@gmail.com" />
			<Banner title="Title" subtitle="Subtitle" />
		</div>
	);
}
